import type { APIRoute } from 'astro';
import { STORYBLOK_VERSION } from 'astro:env/server';
import { PUBLIC_SITE_URL } from 'astro:env/client';

// Prerendered at build (SSG) — emitted into dist/. On the preview site (STORYBLOK_VERSION=draft)
// it renders the preview variant; no Storyblok fetch, so it can never fail the build.
export const prerender = true;

/**
 * Policy for PURE TRAINING crawlers (corpus ingestion, not live answer retrieval). Flip this one
 * constant to switch the stance for GPTBot (OpenAI training) and Google-Extended (Gemini/Vertex
 * training). 'deny' keeps LaMinga's text out of training corpora while STILL allowing the
 * answer-engine retrieval bots below. Confirmed LaMinga decision — see docs/back-office.md.
 */
const TRAINING_CRAWLER_POLICY: 'allow' | 'deny' = 'deny';

/** Answer-engine crawlers that fetch pages to build live AI answers — always allowed (GEO). */
const ANSWER_ENGINE_BOTS = ['OAI-SearchBot', 'ChatGPT-User', 'PerplexityBot', 'ClaudeBot'];

/** Pure training crawlers governed by TRAINING_CRAWLER_POLICY. */
const TRAINING_BOTS = ['GPTBot', 'Google-Extended'];

function productionRobots(): string {
  const sitemap = new URL('/sitemap-index.xml', PUBLIC_SITE_URL).href;
  const trainingRule = TRAINING_CRAWLER_POLICY === 'allow' ? 'Allow: /' : 'Disallow: /';
  const answerEngines = ANSWER_ENGINE_BOTS.map((bot) => `User-agent: ${bot}\nAllow: /`).join(
    '\n\n',
  );
  const training = TRAINING_BOTS.map((bot) => `User-agent: ${bot}\n${trainingRule}`).join('\n\n');

  return `# LaMinga — robots.txt (production). Generated by src/pages/robots.txt.ts at build.

User-agent: *
Allow: /

# AI answer-engine crawlers (live retrieval for AI answers) — explicitly allowed.
${answerEngines}

# Pure training crawlers — policy: ${TRAINING_CRAWLER_POLICY} (see docs/back-office.md).
${training}

Sitemap: ${sitemap}
`;
}

const PREVIEW_ROBOTS = `# LaMinga — robots.txt (preview / draft). This environment must never be indexed.

User-agent: *
Disallow: /
`;

export const GET: APIRoute = () => {
  const body = STORYBLOK_VERSION === 'draft' ? PREVIEW_ROBOTS : productionRobots();
  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
