import { mkdirSync, writeFileSync } from 'node:fs';

// Framing control MUST be an HTTP header: frame-ancestors is ignored inside the
// <meta> CSP that Astro emits, and X-Frame-Options only works as a header.
//   published -> deny all framing (production site)
//   draft     -> allow only the Storyblok Visual Editor to embed the site (preview site)
//
// Keyed off STORYBLOK_VERSION, NOT Netlify's CONTEXT: the preview site builds `main`
// as its production context, so CONTEXT is "production" on both sites — only the
// Storyblok version distinguishes them.
const isPreview = process.env.STORYBLOK_VERSION === 'draft';

const framingLines = isPreview
  ? ['Content-Security-Policy: frame-ancestors https://app.storyblok.com']
  : ['X-Frame-Options: DENY', "Content-Security-Policy: frame-ancestors 'none'"];

const body = framingLines.map((line) => `  ${line}`).join('\n');
const content = `# Generated by scripts/generate-headers.mjs — do not edit (preview=${isPreview}).
/*
${body}
`;

mkdirSync('public', { recursive: true });
writeFileSync('public/_headers', content);
console.log(`[headers] public/_headers written (preview=${isPreview}).`);
