import { mkdirSync, writeFileSync } from 'node:fs';

// Netlify sets CONTEXT to: production | deploy-preview | branch-deploy | dev.
// The SSR preview environment is a branch deploy ("preview") or deploy-preview;
// everything else is treated as production (deny framing).
const context = process.env.CONTEXT ?? 'production';
const isPreview = context === 'deploy-preview' || context === 'branch-deploy';

// Framing control MUST be an HTTP header: frame-ancestors is ignored inside the
// <meta> CSP that Astro emits, and X-Frame-Options only works as a header.
//   production -> deny all framing
//   preview    -> allow only the Storyblok Visual Editor to embed the site
const framingLines = isPreview
  ? ['Content-Security-Policy: frame-ancestors https://app.storyblok.com']
  : ['X-Frame-Options: DENY', "Content-Security-Policy: frame-ancestors 'none'"];

const body = framingLines.map((line) => `  ${line}`).join('\n');
const content = `# Generated by scripts/generate-headers.mjs — do not edit (CONTEXT=${context}).
/*
${body}
`;

mkdirSync('public', { recursive: true });
writeFileSync('public/_headers', content);
console.log(`[headers] public/_headers written for context "${context}" (preview=${isPreview}).`);
